services:
  frontend:
    build: frontend
    restart: always
    depends_on: 
      - database
    ports:
      - "8080:80"
    volumes:
      - ./frontend/html:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      MODE_DEPLOY: development
      MYSQL_HOST: database
      MYSQL_DATABASE: dict
      MYSQL_USER: admin
      MYSQL_PASSWORD: password1234
    command: ["apache2-foreground"]

  database:
    build: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=dict"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=password1234"
      - "MYSQL_ROOT_PASSWORD=password1234"
      - "MYSQL_RANDOM_ROOT_PASSWORD="

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password1234

volumes:
  mysql:
