INSERT INTO Personnels (name, position) VALUES 
('Engr. Pinky T. Jimenez, PECE, Ph.D.', 'Regional Director'),
('Janet T. Catinoy', 'Planning Officer II'),
('Donna Andrea D. Fidel', 'PDO I'),
('Mark John C. Tumaliuan', 'Admin. Aide IV'),
('Mina Flor T. Villafuerte ', 'Chief, Administrative and Finance Division'),
('Engr. Magdalena D. Gomez', 'Chief, Technical Operations Division'),
('Jayfer T. Ammasi', 'Human Resource Management Officer II'),
('Jenny S. Prudenciado', 'Administrative Assistant II'),
('Edmund C. Manuel', 'CEO III (Property Custodian)'),
('Nodel M. Tumaliuan', 'Admin. Aide IV/Driver'),
('Pablo G. Fugaban', 'Admin. Aide IV/Driver'),
('Jemar Jay C. Del Rosario', 'Accountant III'),
('Kimberly Ann B. Calayan', 'PDO II'),
('Julius Cezar C. Baquiran', 'Procurement Management Officer I'),
('Joyce C. Trinidad', 'Administrative Assistant II'),
('Lot-Lot Z. Acera', 'Budget Officer II'),
('Edward C. Manuel', 'CEO III (SDO)'),
('Ronald S. Bariuan', 'ITO II'),
('Michael Angelo R. Langcay', 'Engr II'),
('Dan Mark R. Jose', 'Engr I'),
('Engr.  Joey Mark D. Elchico', 'Engr III'),
('Engr. Cyrill Shane T. Cepeda', 'Engr II'),
('Engr. Neil Kristopher C. Gulmmayen', 'Engr II'),
('Leah G. Galolo', 'Project Development Officer II'),
('Johny C. Batang', 'Engr II'),
('Johanna F. Tulauan', 'ITO I'),
('Jei Ariston C. Jimenez', 'PLO III'),
('Edward Mark D. Argonza', 'PLO I'),
('Ivan Paul M. Santos', 'PLO I'),
('Maricar S. Pecson', 'ISA III'),
('Karl Steven A. Maddela', 'ISA II'),
('Jaymar C. Recolizado', 'ISA II'),
('Diether A. Abad', 'ISA I'),
('Bryan H. Tomas', 'ISA I'),
('Cirilo N. Gazzingan, Jr.', 'ITO II'),
('Edison S. Agaoid', 'PLO II'),
('Mar Elvison A. Bauquiran', 'PLO II'),
('Debora P. Backiawan', 'Planning Assistant'),
('Mariza Nova M. Montes', 'Planning Assistant'),
('Ulysses Niño M. Cadiente', 'PDO I'),
('Rica V. Casuga', 'PDO II'),
('Christine Joyce V. Bueno', 'PDO I/Cashier II'),
('Samantha P. Dawideo', 'PDO I'),
('Sheryl N. Sagaydoro', 'PDO I'),
('Maria Kristine T. Valdez', 'PDO I'),
('Deejay G. Anapi', 'PDO II'),
('Engr. Rogelio T. Layugan', 'ITO II'),
('Roland B. Hubalde', 'ECET I'),
('Adelmo G. Cano', 'CEO II'),
('Ferdinand S. Abad', 'CEO III'),
('Richard P. Baligod', 'ECET I'),
('Alvin B. Bermejo', 'ECET '),
('Joaquin B. Baylon', 'Lineman I'),
('Yancee Kearvin Kyle A. Rafer', 'Planning Assistant'),
('Daniel P. Ramirez', 'CEO III'),
('Eugene L. Pabro', 'CEO III'),
('Conception C. Nazarita', 'CEO III'),
('Rene R. Andres', 'ECET I'),
('Marilyn F. Robles', 'CEO I'),
('Lanie A. Cabacungan', 'CEO III'),
('Medy Jose M. Cabacungan', 'MPO II'),
('Harold P. Pascual', 'Planning Assistant'),
('Jeanne Shannon O. Garcia', 'PDO I'),
('Jonathan F. Del Rosario', 'PDO I')
