ALTER TABLE Projects ADD `project_logo` VARCHAR(64) NOT NULL;
UPDATE Projects SET `project_code` = 'FW4A' WHERE Projects.`project_id` = 8;
UPDATE Projects SET `project_logo` = '/storage/iidb.png' WHERE Projects.`project_id` = 1;
UPDATE Projects SET `project_logo` = '/storage/NIPPSB.png' WHERE Projects.`project_id` = 2;
UPDATE Projects SET `project_logo` = '/storage/eLGU.png' WHERE Projects.`project_id` = 3;
UPDATE Projects SET `project_logo` = '/storage/PNPKI.png' WHERE Projects.`project_id` = 4;
UPDATE Projects SET `project_logo` = '/storage/ilcdb.png' WHERE Projects.`project_id` = 6;
UPDATE Projects SET `project_logo` = '/storage/gecs.png' WHERE Projects.`project_id` = 7;
UPDATE Projects SET `project_logo` = '/storage/fw4a.png' WHERE Projects.`project_id` = 8;
UPDATE Projects SET `project_logo` = '/storage/govnet.png' WHERE Projects.`project_id` = 9;
