CREATE TABLE Sessions (
  session_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  account_id INTEGER UNSIGNED NOT NULL,
  login TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  logout TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT FOREIGN KEY (account_id) REFERENCES Accounts (account_id) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE Accounts ADD `email` VARCHAR(128) NOT NULL;
ALTER TABLE Accounts ADD `deleted` boolean DEFAULT FALSE NOT NULL;
ALTER TABLE Accounts ADD `admin` boolean DEFAULT FALSE NOT NULL;
ALTER TABLE Accounts MODIFY `personnel_id` INTEGER UNSIGNED NULL;
ALTER TABLE Accounts DROP COLUMN current_session;
ALTER TABLE Accounts ADD COLUMN current_session_id INTEGER UNSIGNED NULL;
ALTER TABLE Accounts ADD CONSTRAINT FOREIGN KEY (current_session_id) REFERENCES Sessions(session_id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE JobOrder
ADD COLUMN client_name VARCHAR(128) NOT NULL,
ADD COLUMN client_position VARCHAR(128) NOT NULL,
ADD COLUMN client_contact VARCHAR(64) NOT NULL,
ADD COLUMN client_lgu VARCHAR(128) NOT NULL,
ADD COLUMN request_mode ENUM('On Site') NOT NULL,
ADD COLUMN request_date DATE NOT NULL,
ADD COLUMN issued_by INTEGER UNSIGNED NOT NULL,
ADD COLUMN approved_by INTEGER UNSIGNED NOT NULL,
ADD COLUMN job_order_number VARCHAR(64) NOT NULL;

ALTER TABLE JobOrder
ADD CONSTRAINT FOREIGN KEY (issued_by) REFERENCES Personnels(personnel_id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT FOREIGN KEY (approved_by) REFERENCES Personnels(personnel_id) ON DELETE CASCADE ON UPDATE CASCADE;

-- password is 'adminpassword'
INSERT INTO Accounts (personnel_id, password_hash, email, admin)
VALUES (NULL, '$2y$10$GFJ3tJ6Il3769xGc/GC8zOLBaoJqMf35YsrffO1SelZMhN/Di1dHi', 'admin@email.com', TRUE);
